### ISSUE TITLE
[ecdysis SLRC-SLRC] meta.xml mentioned materialSample.csv but not provide one in content associated with dwc-a endpoint at <https://ecdysis.org/content/dwca/SLRC-SLRC_DwC-A.zip> <http://purl.org/pav/hasVersion> <hash://sha256/b672bcdb1e83f6ee412c0db76438f4d55f6b10d4be501fa76c0b5339d5203de3> <urn:uuid:ea8f89d5-8f6d-48b1-8d86-91e5577e2454> .

### ISSUE THREAD

**Issue by jhpoelen** [Symbiota/Symbiota#871]
found in collection overlaps between scan and ecdysis -

```
$ preston cat 'zip:hash://sha256/b672bcdb1e83f6ee412c0db76438f4d55f6b10d4be501fa76c0b5339d5203de3!/meta.xml' | xmllint --format - | grep materialSample.csv  
```

produces:

```
      <location>materialSample.csv</location>
```

but the dwc-a does not contain a materialSample.csv file - 

```
$ unzip -l dwca.zip 
Archive:  dwca.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   838487  2024-01-02 09:36   occurrences.csv
   154906  2024-01-02 09:36   identifications.csv
   165273  2024-01-02 09:36   multimedia.csv
    12181  2024-01-02 09:36   meta.xml
     4218  2024-01-02 09:36   eml.xml
      396  2024-01-02 09:36   CITEME.txt
---------                     -------
  1175461                     6 files
```

:warning: incomprehensible error log  below

```
[main] WARN bio.guoda.preston.stream.ArchiveStreamHandler - failed to process <zip:hash://sha256/b672bcdb1e83f6ee412c0db76438f4d55f6b10d4be501fa76c0b5339d5203de3!/meta.xml>
bio.guoda.preston.stream.ContentStreamException: failed to handle dwc records from <zip:hash://sha256/b672bcdb1e83f6ee412c0db76438f4d55f6b10d4be501fa76c0b5339d5203de3!/materialSample.csv>
	at org.gbif.dwc.DwCArchiveStreamHandler.rethrowStreamException(DwCArchiveStreamHandler.java:116)
	at org.gbif.dwc.DwCArchiveStreamHandler.streamRecords(DwCArchiveStreamHandler.java:107)
	at org.gbif.dwc.DwCArchiveStreamHandler.handleAssumedDwCArchive(DwCArchiveStreamHandler.java:83)
	at org.gbif.dwc.DwCArchiveStreamHandler.handle(DwCArchiveStreamHandler.java:56)
	at bio.guoda.preston.stream.ContentStreamHandlerImpl.handle(ContentStreamHandlerImpl.java:38)
	at bio.guoda.preston.cmd.DwcRecordExtractor$DwCStreamHandlerImpl.handle(DwcRecordExtractor.java:67)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handleArchiveEntries(ArchiveStreamHandler.java:62)
	at bio.guoda.preston.stream.ArchiveStreamHandler.handle(ArchiveStreamHandler.java:32)
	at bio.guoda.preston.stream.ContentStreamHandlerImpl.handle(ContentStreamHandlerImpl.java:38)
	at bio.guoda.preston.cmd.DwcRecordExtractor$DwCStreamHandlerImpl.handle(DwcRecordExtractor.java:67)
	at bio.guoda.preston.cmd.ProcessorExtracting.on(ProcessorExtracting.java:52)
	at bio.guoda.preston.cmd.CmdDwcRecordStream$1.emit(CmdDwcRecordStream.java:47)
	at bio.guoda.preston.process.EmittingStreamAbstract.copyOnEmit(EmittingStreamAbstract.java:29)
	at bio.guoda.preston.process.EmittingStreamOfAnyVersions.parseAndEmit(EmittingStreamOfAnyVersions.java:35)
	at bio.guoda.preston.cmd.CmdDwcRecordStream.run(CmdDwcRecordStream.java:52)
	at bio.guoda.preston.cmd.CmdDwcRecordStream.run(CmdDwcRecordStream.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at bio.guoda.preston.Preston.run(Preston.java:95)
	at bio.guoda.preston.Preston.main(Preston.java:86)
Caused by: bio.guoda.preston.store.DereferenceException: failed to dereference [zip:hash://sha256/b672bcdb1e83f6ee412c0db76438f4d55f6b10d4be501fa76c0b5339d5203de3!/materialSample.csv]
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:25)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:10)
	at org.gbif.dwc.DwCArchiveStreamHandler.createReader(DwCArchiveStreamHandler.java:151)
	at org.gbif.dwc.DwCArchiveStreamHandler.streamRecords(DwCArchiveStreamHandler.java:101)
	... 24 more
Caused by: java.io.IOException: cannot find content identified by [<zip:hash://sha256/b672bcdb1e83f6ee412c0db76438f4d55f6b10d4be501fa76c0b5339d5203de3!/materialSample.csv>]
	at bio.guoda.preston.stream.ContentStreamFactory.create(ContentStreamFactory.java:74)
	at bio.guoda.preston.store.ContentHashDereferencer.get(ContentHashDereferencer.java:23)
	... 27 more
```

**Comment by jhpoelen** [comment]
Issue of the missing materialSample.csv appears to have been resolved somewhere in the last 2.5 years. 

Yay! 

I confirmed using:

```
preston track "https://ecdysis.org/content/dwca/SLRC-SLRC_DwC-A.zip"\
 | preston dwc-stream\
 | head -1\
 | jq .
```

```json
{
  "http://www.w3.org/ns/prov#wasDerivedFrom": "line:zip:hash://sha256/65cf22d1a323671a3c929989b300b4bf986e3c647a3a3147b5c1028055b1fc2e!/occurrences.csv!/L2",
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#type": "http://rs.tdwg.org/dwc/terms/Occurrence",
  "http://rs.tdwg.org/dwc/text/id": "362155",
  "http://rs.tdwg.org/dwc/terms/locality": "Reserva Forestal Fortuna, Smithsonian Tropical Research Institute Station",
  "http://rs.tdwg.org/dwc/terms/georeferenceRemarks": null,
  "http://rs.tdwg.org/dwc/terms/collectionID": "1af72f20-5059-4d55-b6fd-670df22ff189",
  "http://rs.tdwg.org/dwc/terms/municipality": null,
  "http://rs.tdwg.org/dwc/terms/maximumElevationInMeters": null,
  "http://rs.tdwg.org/dwc/terms/stateProvince": "Chiriqui",
  "http://rs.tdwg.org/dwc/terms/dataGeneralizations": null,
  "http://rs.tdwg.org/dwc/terms/verbatimCoordinates": null,
  "http://rs.tdwg.org/dwc/terms/basisOfRecord": "PreservedSpecimen",
  "http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters": "50",
  "http://rs.tdwg.org/dwc/terms/disposition": null,
  "https://symbiota.org/terms/recordID": "f6e6455f-9271-4ad8-82f3-61da661ef097",
  "http://rs.tdwg.org/dwc/terms/locationID": null,
  "http://rs.tdwg.org/dwc/terms/cultivarEpithet": null,
  "http://rs.tdwg.org/dwc/terms/countryCode": "PA",
  "http://rs.tdwg.org/dwc/terms/georeferenceVerificationStatus": null,
  "http://rs.tdwg.org/dwc/terms/subgenus": null,
  "http://rs.tdwg.org/dwc/terms/preparations": null,
  "http://purl.org/dc/terms/language": null,
  "http://rs.tdwg.org/dwc/terms/taxonID": null,
  "http://rs.tdwg.org/dwc/terms/identifiedBy": "Sangmi Lee",
  "http://rs.tdwg.org/dwc/terms/establishmentMeans": null,
  "http://rs.tdwg.org/dwc/terms/geodeticDatum": "WGS84",
  "http://rs.tdwg.org/dwc/terms/eventDate": "2013-05-23",
  "http://rs.tdwg.org/dwc/terms/associatedSequences": null,
  "http://rs.tdwg.org/dwc/terms/georeferencedBy": "Sangmi Lee",
  "http://rs.tdwg.org/dwc/terms/phylum": "Arthropoda",
  "http://rs.tdwg.org/dwc/terms/islandGroup": null,
  "http://rs.tdwg.org/dwc/terms/behavior": null,
  "https://symbiota.org/terms/recordEnteredBy": "sangmi.lee",
  "http://rs.tdwg.org/dwc/terms/identificationQualifier": null,
  "http://rs.tdwg.org/dwc/terms/year": "2013",
  "http://rs.tdwg.org/dwc/terms/occurrenceRemarks": "GOA002-17 (SL0602)",
  "http://rs.tdwg.org/dwc/terms/catalogNumber": "SLRC0000094",
  "http://rs.tdwg.org/dwc/terms/ownerInstitutionCode": "Sangmi Lee",
  "http://rs.tdwg.org/dwc/terms/typeStatus": null,
  "http://rs.tdwg.org/dwc/terms/vitality": null,
  "http://rs.tdwg.org/dwc/terms/lifeStage": null,
  "http://rs.tdwg.org/dwc/terms/verbatimElevation": null,
  "http://rs.tdwg.org/dwc/terms/minimumElevationInMeters": null,
  "http://rs.tdwg.org/dwc/terms/genus": null,
  "http://rs.tdwg.org/dwc/terms/decimalLongitude": "-82.24015",
  "http://rs.tdwg.org/dwc/terms/collectionCode": "SLRC",
  "http://rs.tdwg.org/dwc/terms/eventID": null,
  "http://rs.tdwg.org/dwc/terms/kingdom": "Animalia",
  "http://rs.tdwg.org/dwc/terms/class": "Insecta",
  "http://rs.tdwg.org/dwc/terms/specificEpithet": null,
  "http://purl.org/dc/terms/modified": "2017-11-01 14:16:39",
  "http://purl.org/dc/terms/references": "https://ecdysis.org/collections/individual/index.php?occid=362155",
  "http://rs.tdwg.org/dwc/terms/waterBody": null,
  "http://rs.tdwg.org/dwc/terms/dateIdentified": "2017",
  "http://rs.tdwg.org/dwc/terms/informationWithheld": null,
  "http://purl.org/dc/terms/rightsHolder": null,
  "http://rs.tdwg.org/dwc/terms/identificationRemarks": null,
  "http://rs.tdwg.org/dwc/terms/higherClassification": "Animalia|Arthropoda|Hexapoda|Insecta|Pterygota|Neoptera|Lepidoptera|Gelechioidea",
  "http://rs.tdwg.org/dwc/terms/family": "Gelechiidae",
  "http://purl.org/dc/terms/accessRights": null,
  "http://rs.tdwg.org/dwc/terms/verbatimDepth": null,
  "http://rs.tdwg.org/dwc/terms/verbatimTaxonRank": null,
  "http://rs.tdwg.org/dwc/terms/verbatimEventDate": null,
  "http://rs.tdwg.org/dwc/terms/county": null,
  "http://rs.tdwg.org/dwc/terms/occurrenceID": "a69198ea-88c7-48ad-a520-32cd67e23076",
  "http://rs.tdwg.org/dwc/terms/maximumDepthInMeters": null,
  "http://rs.tdwg.org/dwc/terms/georeferenceSources": "Label",
  "http://rs.tdwg.org/dwc/terms/minimumDepthInMeters": null,
  "http://rs.tdwg.org/dwc/terms/taxonRank": null,
  "http://rs.tdwg.org/dwc/terms/endDayOfYear": null,
  "http://rs.tdwg.org/dwc/terms/habitat": null,
  "http://rs.tdwg.org/dwc/terms/month": "5",
  "http://rs.tdwg.org/dwc/terms/reproductiveCondition": null,
  "http://rs.tdwg.org/dwc/terms/decimalLatitude": "8.73465",
  "http://rs.tdwg.org/dwc/terms/scientificNameAuthorship": null,
  "http://rs.tdwg.org/dwc/terms/recordNumber": null,
  "http://rs.tdwg.org/dwc/terms/taxonRemarks": null,
  "http://rs.tdwg.org/dwc/terms/sex": null,
  "http://rs.tdwg.org/dwc/terms/institutionCode": "SLRC",
  "http://rs.tdwg.org/dwc/terms/samplingProtocol": null,
  "http://rs.tdwg.org/dwc/terms/infraspecificEpithet": null,
  "http://purl.org/dc/elements/1.1/rights": "http://creativecommons.org/publicdomain/zero/1.0/",
  "http://rs.tdwg.org/dwc/terms/dynamicProperties": null,
  "http://rs.tdwg.org/dwc/terms/individualCount": null,
  "http://rs.tdwg.org/dwc/terms/island": null,
  "http://rs.tdwg.org/dwc/terms/georeferenceProtocol": null,
  "http://rs.tdwg.org/dwc/terms/order": "Lepidoptera",
  "http://rs.tdwg.org/dwc/terms/country": "Panama",
  "http://rs.tdwg.org/dwc/terms/day": "23",
  "http://rs.tdwg.org/dwc/terms/associatedOccurrences": null,
  "http://rs.tdwg.org/dwc/terms/recordedBy": "Sangmi Lee",
  "http://rs.tdwg.org/dwc/terms/continent": "North America",
  "http://rs.tdwg.org/dwc/terms/otherCatalogNumbers": "ASUHIC0090379",
  "http://rs.tdwg.org/dwc/terms/scientificName": "Anthistarcha sp1",
  "http://rs.tdwg.org/dwc/terms/identificationReferences": null,
  "http://rs.tdwg.org/dwc/terms/startDayOfYear": "143",
  "http://rs.tdwg.org/dwc/terms/locationRemarks": null,
  "http://rs.tdwg.org/dwc/terms/fieldNumber": null,
  "http://rs.tdwg.org/dwc/terms/associatedTaxa": null
}
```
